
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://stefanprodan.github.io/podinfo'
    targetRevision: 6.3.0
    chart: podinfo
    helm:
      values: |
        backend: 'http://backend-podinfo:9898/echo'
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
  project: default