
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo_2
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://stefanprodan.github.io/podinfo'
    targetRevision: 6.3.0
    chart: podinfo
    helm:
      values: |
        cache: "tcp://redis-master:6379"
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
  project: default